### PR TITLE
proposed folder structure

### PR DESCRIPTION
**Pull request by 2potatocakes**
Putting up this PR to help track feedback surrounding folder structure. As far as I can tell, there's not much pushback to the folder structure.

screen shot 2017-08-02 at 3 49 37 pm

I would like to decide if we are going to include a `_defaults.json` file in the `data/designs/hosted/` and `data/designs/sites/` folders.

This would essentially allow us to apply some default values to all designs and then overwrite them individually as each design is serialized. 

A valid argument against this approach is that perhaps the concept of "defaults" is something that should be pushed back up to the vendor and shouldn't be handled by the Catalogue. The added benefit of pushing this back to the vendors is that it would mean that all changes that affect `designs` will be visible in any future PR's whereas changes to the "defaults" files may not be evident in the designs that they affect.

### CODE REVIEW

**Comment by blimpage** [comment]
[Reiterating what I said in Slack](https://envato.slack.com/archives/C4BAJM094/p1501646018949970), I'm on the "defaults don't belong in the catalogue" side of the fence.

The benefit of having defaults is that you can specify a value in a single place and have it be applied to multiple records. If a human wants to change that value, they can update it in a single place and the change will flow to all of those records. The process is optimised for ease of human-editability.

However the files that we put into the catalogue aren't intended to be edited by humans, so to me it doesn't make sense to optimise for human-editability here.

**Comment by smlparry** [comment]
Eh, I could go either way on this. 

If we go with the "defaults don't belong in here" approach we will now have to create 2 systems (`hosted-themes` and the Sites exporter) that apply defaults to their data, rather than just the 1.

But again, no strong opinion, I could be swayed either way. Just don't want to push too much work onto sites if it is not needed

**Comment by blimpage** [comment]
> If we go with the "defaults don't belong in here" approach we will now have to create 2 systems (`hosted-themes` and the Sites exporter) that apply defaults to their data, rather than just the 1.

`¯\_(ツ)_/¯` Those two systems will probably have a lot in common regardless.

**Comment by 2potatocakes** [comment]
We decided to push the idea of maintaining a list of `defaults` back up to the vendors to manage themselves. With the reason being, once vendors begin submitting PR requests containing `Design` data, we would like the PR's to include all changes that will affect those particular designs in the PR.

**Pull request closed without merging**
